Lens 44
ConsenSys/lineaster pull request #40
Opened 2023-05-25 08:00 UTC by mlallai

## What does this PR do?

[UI] Adapt notification page styles

## Related ticket

Fixes [LENS-XXX](https://consensyssoftware.atlassian.net/browse/LENS-XXX)

## Type of change

- [ ] Bug fix (non-breaking change, which fixes an issue)
- [ ] New feature (non-breaking change, which adds functionality)
- [x] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-05-25 10:03 UTC, alainncls approved these changes

2023-05-25 11:50 UTC, Akaryatrh commented
Don't we have to duplicate the content modified from `packages/ui/src/*` to `apps/web/packages/ui/src/*` otherwise we will have issues on build phase?

2023-05-25 11:51 UTC, Akaryatrh requested changes
Don't we have to duplicate the content modified from `packages/ui/src/*` to `apps/web/packages/ui/src/*` otherwise we will have issues on build phase?

2023-05-25 12:03 UTC, Akaryatrh requested changes

2023-05-25 12:03 UTC, Akaryatrh commented on packages/ui/src/TabButton.tsx
> +        'text-brand flex items-center space-x-2 rounded-[2px] px-4 py-2 text-sm font-medium hover:bg-blue-500 hover:bg-opacity-100 dark:hover:bg-opacity-20 sm:px-3 sm:py-1.5'
I'd go with this instead
```suggestion
{ 'bg-brand-500 text-dark dark:text-dark hover:cursor-default dark:bg-white': active },
        'text-dark dark:hover:text-dark hover:bg-brand-500 flex items-center space-x-2 rounded-full px-4 py-2 text-sm font-medium dark:text-white sm:px-3 sm:py-1.5'
```
<img width="715" alt="Capture d’écran 2023-05-25 à 14 02 19" src="https://github.com/ConsenSys/lineaster/assets/574787/1dc1be80-e93c-455e-875e-f02172767f4d">
<img width="734" alt="Capture d’écran 2023-05-25 à 14 02 12" src="https://github.com/ConsenSys/lineaster/assets/574787/844f0f7b-1d36-4e6b-b418-60e37800036f">

2023-05-26 07:40 UTC, Akaryatrh commented on apps/web/packages/ui/src/TabButton.tsx
> +        }
Still not ok to me 😅  here's the right styles IMO:
```suggestion
        {
          'text-dark bg-brand-500 flex items-center space-x-2 rounded-full px-4 py-2 text-sm font-medium hover:cursor-default sm:px-3 sm:py-1.5':
            active
        },
        {
          'text-dark dark:hover:text-dark hover:bg-brand-500 flex items-center space-x-2 rounded-full px-4 py-2 text-sm font-medium dark:text-white sm:px-3 sm:py-1.5':
            !active
        }
```

2023-05-26 08:25 UTC, Akaryatrh approved these changes

2023-05-26 12:43 UTC, merged