LENS-47: [UI] Adapt Profile page styles
ConsenSys/lineaster pull request #78
Opened 2023-06-09 13:38 UTC by igorms-cons

## What does this PR do?

## Related ticket

Fixes [LENS-47](https://consensyssoftware.atlassian.net/browse/LENS-47

## Type of change

- [ ] Bug fix (non-breaking change, which fixes an issue)
- [ ] New feature (non-breaking change, which adds functionality)
- [ ] Enhancement (non-breaking small changes to existing functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

2023-06-15 10:07 UTC, alainncls requested changes

2023-06-15 10:07 UTC, alainncls commented on apps/web/.env.uat
File to remove?

2023-06-15 10:35 UTC, Akaryatrh requested changes

2023-06-15 10:35 UTC, Akaryatrh commented on apps/web/src/components/Profile/Details.tsx
> +                <Trans>EDIT PROFILE</Trans>
Please use `uppercase` class for this 🙂

2023-06-15 10:35 UTC, Akaryatrh commented on apps/web/src/components/Publication/Actions/Menu/Permalink.tsx
> +          <div>PERMALINK</div>
Please use `uppercase` class for this 🙂

2023-06-19 09:09 UTC, Akaryatrh approved these changes

2023-06-19 10:22 UTC, alainncls approved these changes

2023-06-19 10:22 UTC, merged